### ISSUE TITLE
2,000 socket writes and Nodejs goes flop.

### ISSUE THREAD

**Issue by IngwiePhoenix** [nodejs/node-v0.x-archive#14501]
I was going to stress-test my local RPC server by literally flooding it.

``` javascript
var hprose = require("hprose"),
    client = new HproseTcpClient("tcp://127.0.0.1:9999"),
    proxy = client.useService();

client.on("error", function(func, e) {
    console.log("Error:", arguments);
    console.log(e.stack);
});

for(j=0; j<2; j++) {
    for(i=0; i<=1000; i++) {
        proxy.foo(function(res, args){
            console.log(this.i+"...");
        }.bind({i:i}));
    }
}
```

...but I get this:

```
$ node --harmony htest.js 
(libuv) Failed to create kqueue (23)
(libuv) Failed to create kqueue (23)

Error: write EBADF
    at errnoException (net.js:904:11)
    at WriteStream.Socket._write (net.js:645:26)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at WriteStream.Writable.write (_stream_writable.js:182:11)
    at WriteStream.Socket.write (net.js:615:40)
    at Console.log (console.js:53:16)
    at HproseTcpClient.j (/Users/Ingwie/Work/BIRD3/hprose_test/htest.js:7:13)
    at HproseTcpClient.emit (events.js:98:17)
    at /Users/Ingwie/Work/BIRD3/node_modules/hprose/lib/client/HproseClient.js:392:34
```

EBADF is a bit of a weird error name that I can not decipher. Reading in google, it means bad file descriptor. Is libuv simply killing my socket connection or what is the problem here?

**Comment by trevnorris** [comment]
Have a test case that doesn't require a third-party module? Does a debug build also fail? What are the machine specs you're running on?
