### ISSUE TITLE
0.12.2 throws Error: setBlocking ENOSYS on Gentoo Linux 3.19.3

### ISSUE THREAD

**Issue by aahutsal** [nodejs/node-v0.x-archive#14571]
any project `grunt serve` fails.

```
.Options: limit=4
    Warning: net.js:164
            throw errnoException(err, 'setBlocking');
                  ^
    Error: setBlocking ENOSYS
        at exports._errnoException (util.js:746:11)
        at new Socket (net.js:164:15)
        at createWritableStdioStream (node.js:463:18)
        at process.stdout (node.js:502:16)
        at new Log (/home/archer/dev/softsky/socibo/socibo.co/node_modules/grunt/node_modules/grunt-legacy-log/index.js:37:23)
        at Object.<anonymous> (/home/archer/dev/softsky/socibo/socibo.co/node_modules/grunt/lib/grunt.js:31:11)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12) Use --force to continue.

        Aborted due to warnings.
```

works well on nodejs-0.12.0

**Comment by MJDSys** [comment]
This appears to be a downstream issue with Gentoo's packaging ( https://bugs.gentoo.org/show_bug.cgi?id=545618 ).  This issue occurs in several packages unless libuv is upgraded as described in the bug report.

**Comment by pee** [comment]
I have the same problem, works ok in 0.12.1

**Comment by rendom** [comment]
Seems to work fine in the latest update. (0.12.2-r1)
