### ISSUE TITLE
v0.12.2 cannot kill ffmpeg process - process._tickCallback (node.js:355:11)

### ISSUE THREAD

**Issue by g00dnatur3** [nodejs/node-v0.x-archive#25092]
Hi,

I'm trying to kill a spawned ffmpeg process and I am getting this error:

/home/developer/workspace/leaf-hub/node_modules/longjohn/dist/longjohn.js:184
        e.stack;
         ^
process._tickCallback (node.js:355:11)

Here is how I initialize the process:

```
    var ffmpegParams = [
        '-loglevel', 'quiet',
        '-re',
        '-r', '15',
        '-i', 'pipe:0',
        '-vcodec', 'copy',
        '-bufsize', '0',
        '-f', 'h264',
        'pipe:1'
    ]
    var ffmpeg = spawn('ffmpeg', ffmpegParams)
    var index = camera.buf.length - secondsAgo
    for (var i=index; i<camera.buf.length; i++) {
        ffmpeg.stdin.write(camera.buf[i])
    }
    var bufchanged = function(buf) {
        var index = buf.length - secondsAgo
        ffmpeg.stdin.write(buf[buf.length-1])
    }
    camera.on('bufchanged', bufchanged)
    ffmpeg.stdout.on('data', ondata)
    var stream = {ffmpeg: ffmpeg, close: function() {
        camera.removeListener('bufchanged', bufchanged)
        ffmpeg.stdout.removeListener('data', ondata)
    }}
    streams.push(stream)
    var stopId = streams.length-1;
    return stopId
```

Here is how I kill the ffmpeg process

```
    var stream = streams[index]
    console.log('KILLING STREAM: ' + index)
    if (stream.close) {
        stream.close()
    }
    stream.ffmpeg.on('error', function() { console.log('Failed to kill FFMPEG') })
    stream.ffmpeg.on('close', function() { console.log('FFMPEG is closed') })
    //stream.ffmpeg.kill() --> this is not working for some reason
    setTimeout(function() {
        var cmd = 'kill -9 ' + stream.ffmpeg.pid
        console.log('killing ffmpeg with cmd: ' + cmd)
        child = exec(cmd, function (error, stdout, stderr) {
            if (error !== null) {
              console.log('exec error: ' + error)
            }
        })
    }, 2000)
```

The reason I put the kill command in a timeout is because the bug is less likely to happen, but still eventually happens.. Without the timeout the bug will occur 100% of the time.

stream.ffmpeg.kill() --> this will not kill the kill the ffmpeg, it will do nothing
stream.ffmpeg.kill('SIGKILL') --> this will produce the same result as 'kill -9'

I have killed ffmpeg in other places of my code, I am thinking it is likely also a bug in ffmpeg.

I notice if i run the ffmpeg without the '-re' command option that I can kill it without having this bug.
But i absolutely need the '-re' option, its quite important.

In anycase I do not think my nodejs app should explode and not allow me to catch this error (which i still do not understand why i have an error in the first place, my clean-up looks fine)

I hope we can find the cause of this problem.

Thanks

**Comment by g00dnatur3** [comment]
Here is the debug log from npm:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart leaf-hub@0.0.1
6 info start leaf-hub@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info leaf-hub@0.0.1 Failed to exec start script
9 verbose stack Error: leaf-hub@0.0.1 start: `node ./bin/www`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid leaf-hub@0.0.1
11 verbose cwd /home/developer/workspace/leaf-hub
12 error Linux 3.10.0-123.20.1.el7.x86_64
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v0.12.2
15 error npm  v2.7.4
16 error code ELIFECYCLE
17 error leaf-hub@0.0.1 start: `node ./bin/www`
17 error Exit status 1
18 error Failed at the leaf-hub@0.0.1 start script 'node ./bin/www'.
18 error This is most likely a problem with the leaf-hub package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./bin/www
18 error You can get their info via:
18 error     npm owner ls leaf-hub
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
