### ISSUE TITLE
VM: Breaking Change in 0.12

### ISSUE THREAD

**Issue by jugglinmike** [nodejs/node-v0.x-archive#25659]
As of Node 0.12.0, `vm.runInNewContext` no longer honors directive prologues
specified as the first statement(s) in the input.

Test case:

```js
var vm = require('vm');

vm.runInNewContext('"use strict"; unresolvable = null;');
```

    $ /opt/joyent/node-0.10.40/bin/node test.js
    vm.runInNewContext('"use strict"; unresolvable = null;');
       ^
    ReferenceError: unresolvable is not defined
        at evalmachine.<anonymous>:1:28
        at Object.<anonymous> (/home/mike/projects/bocoup/google-es6/test262-harness/tmp.js:3:4)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
        at node.js:935:3
    $ /opt/joyent/node-0.12.0/bin/node test.js
    $ echo $?
    0
    $ /opt/joyent/node-0.12.7/bin/node test.js
    $ echo $?
    0

I've bisected this down to, 85898d196718ef2e2129ed98b8865ee4b2658f0b, an update
to V8. My experience with that project is even more minimal than with this one,
so I'm not the right person to take this any further. Hope this helps!

    commit 85898d196718ef2e2129ed98b8865ee4b2658f0b
    Author: Timothy J Fontaine <tjfontaine@gmail.com>
    Date:   Thu Sep 26 09:18:06 2013 -0700

        v8: upgrade to 3.20.17.13

        fixes #6235

**Comment by jugglinmike** [comment]
Looks like this has been fixed in the latest release of io.js:

```
$ /opt/iojs/iojs-2.3.4/bin/iojs test.js
"use strict"; unresolvable = null;
                           ^
ReferenceError: unresolvable is not defined
    at evalmachine.<anonymous>:1:28
    at ContextifyScript.Script.runInNewContext (vm.js:18:15)
    at Object.exports.runInNewContext (vm.js:49:17)
    at [eval]:1:15
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:430:26)
    at node.js:567:27
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)

**Comment by brendanashworth** [comment]
If it is fixed in node v4 (io.js), then I'm going to close this as a non-issue. If you would like something to be backported, please open a new issue @ https://github.com/nodejs/node.

**Comment by jugglinmike** [comment]
Works for me!
