### ISSUE TITLE
Error: connect EADDRINUSE 

### ISSUE THREAD

**Issue by jbfm21** [nodejs/node-v0.x-archive#25836]
Hello, 

On node v.0.12.X, after I updated my Windows to Windows 10,  everytime that i try to install a package (npm install bower, npm install gulp) or try to make a connection, like the program above
    var mongoose = require('mongoose');
    mongoose.connect('mongodb://localhost/test');

The node.js is throwing the exception     Error: connect EADDRINUSE: 

---Example of the error while installing package
    Error: connect EADDRINUSE
        at exports._errnoException (util.js:746:11)
        at connect (net.js:842:19)
        at net.js:955:9
        at GetAddrInfoReqWrap.asyncCallback [as callback](dns.js:81:16)
        at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:99:10)

**In node v.0.10.x everything works fine**

I do not have any other node.js applications running in the system,  already turned off the firewall, and there is no other application listening/connected in the same port.

Someone  can help me?

**Comment by jbfm21** [comment]
After a lot of investigation, i removed my network driver and reinstalled. Everything works now.
