### ISSUE TITLE
fs.stat difference on windows

### ISSUE THREAD

**Issue by isaacs** [nodejs/node-v0.x-archive#3374]
On unix:

```
$ mkdir dir
$ touch file
$ node
> fs = require("fs");1
1
> fs.statSync("dir/.")
{ dev: 234881026,
  ino: 43198066,
  mode: 16877,
  nlink: 2,
  uid: 24561,
  gid: 20,
  rdev: 0,
  size: 68,
  blksize: 4096,
  blocks: 0,
  atime: Tue Jun 05 2012 08:51:12 GMT-0700 (PDT),
  mtime: Tue Jun 05 2012 08:51:12 GMT-0700 (PDT),
  ctime: Tue Jun 05 2012 08:51:12 GMT-0700 (PDT) }
> fs.statSync("file/.")
Error: ENOTDIR, not a directory 'file/.'
    at Object.fs.statSync (fs.js:467:18)
    at repl:1:5
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:249:12)
    at Interface.EventEmitter.emit (events.js:87:17)
    at Interface._onLine (readline.js:183:10)
    at Interface._line (readline.js:502:8)
    at Interface._ttyWrite (readline.js:719:14)
    at ReadStream.<anonymous> (readline.js:105:12)
    at ReadStream.EventEmitter.emit (events.js:114:20)
```

On Windows:

```

C:\Users\Isaac Schlueter>touch file

C:\Users\Isaac Schlueter>mkdir dir

C:\Users\Isaac Schlueter>node
> fs = require('fs');1
1
> fs.stat('dir/.', console.error)
undefined
> null { dev: 0,
  ino: 0,
  mode: 16822,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  size: 0,
  atime: Tue, 05 Jun 2012 15:52:29 GMT,
  mtime: Tue, 05 Jun 2012 15:52:29 GMT,
  ctime: Tue, 05 Jun 2012 15:52:29 GMT }
> fs.stat('file/.', console.error)
undefined
> null { dev: 0,
  ino: 0,
  mode: 33206,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  size: 0,
  atime: Tue, 05 Jun 2012 15:52:27 GMT,
  mtime: Tue, 05 Jun 2012 15:52:27 GMT,
  ctime: Tue, 05 Jun 2012 15:52:27 GMT }
```

Expected: should raise ENOTDIR.

**Comment by Globik** [comment]
Io.js 1.6, windows 7 32bit, stats.ino works fine.
