### ISSUE TITLE
friendlier error if you pipe an objectMode stream to a non objectMode stream

### ISSUE THREAD

**Issue by maxogden** [nodejs/node-v0.x-archive#5028]
in 0.10.0 if you `.pipe` a `stream.Readable` with `objectMode: true` to a non `objectMode: true` stream you get this error:

``` js
TypeError: invalid data
    at WriteStream.Socket.write (net.js:580:11)
    at write (_stream_readable.js:547:24)
    at flow (_stream_readable.js:556:7)
    at Readable.pipeOnReadable (_stream_readable.js:588:5)
    at Readable.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:382:10)
    at emitReadable (_stream_readable.js:377:5)
    at readableAddChunk (_stream_readable.js:142:7)
    at Readable.push (_stream_readable.js:112:10)
```

is there any reason it can't be:

``` js
TypeError: object written to non-object stream
```

?

**Comment by dzuluaga** [comment]
+1

**Comment by jasnell** [comment]
Definitely still an issue in v0.12 and io.js. Marking as a feature-request.
