### ISSUE TITLE
send socket to child process error

### ISSUE THREAD

**Issue by ruiqian** [nodejs/node-v0.x-archive#6701]
i create a tcp server on parent process, and send socket to child process
```javascript
net.createServer(function(s) {
        s.pause();
            var worker = workers.shift();
            try{
                worker.send('c',s);
            }catch(ex){}
            workers.push(worker);            
    }).listen(80);
```
and i catch socket in child process like this:
```javascript
process.on("message", function(msg,socket) {
        process.nextTick(function(){
            if(msg == 'c' && socket) {
                socket.readable = socket.writable = true;
                socket.resume();
                //server.connections++;
                socket.server = server;
                server.emit("connection", socket);
                socket.emit("connect");
            }
        });
    });
```
now, there is an error when my server running a while
```
TypeError: Cannot set property 'onread'
of null
TypeError: Cannot set property 'onread' of null
    at ChildProcess.handleConversion.net.Socket.send (child_process.js:134:21)
    at ChildProcess.target.send (child_process.js:439:52)
    at child_process.js:372:16
    at Array.forEach (native)
    at ChildProcess.<anonymous> (child_process.js:371:13)
    at ChildProcess.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at Pipe.channel.onread (child_process.js:345:11)
```

**Comment by jasnell** [comment]
@ruiqian ... I know it's been a while, but is this still an issue for you?

**Comment by brendanashworth** [comment]
I'm going to go ahead and close this as inactive; and, this doesn't seem like a "critical bug" that would justify a backport to a maintenance stream.

**Comment by mvtcode** [comment]
I'm using v1.3.7 crash:

TypeError: Cannot set property 'onread' of null
    at ChildProcess.handleConversion.net.Socket.send (child_process.js:134:21)
    at ChildProcess.target.send (child_process.js:439:52)
    at child_process.js:372:16
    at Array.forEach (native)
    at ChildProcess.<anonymous> (child_process.js:371:13)
    at ChildProcess.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at Pipe.channel.onread (child_process.js:345:11)
