### ISSUE TITLE
There was an internal error in Node's debugger. Please report this bug.

### ISSUE THREAD

**Issue by mwq27** [nodejs/node-v0.x-archive#8030]
Using OSX 10.9.4, node v0.10.29, and npm v2.0.0-alpha-5.  I tried a protractor debug command

**Comment by pellekrogholt** [comment]
@indutny I came across a similar issuse which I can reproduce as follow:

## versions / os

a node project using 

```
$ node --version
v5.2.0
$ npm --version
3.3.12

packages.json ->    
...
"protractor": "^3.0.0",
"webdriver-manager": "^7.0.1",
"jasmine-core": "^2.3.4",
"karma": "0.13.8",
"karma-jasmine": "^0.3.5",
```

os: ubuntu 14.

## problem

execute:

```
./node_modules/.bin/protractor debug protractor.conf.js 
```

raises:

```
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
Starting debugger agent.
Debugger listening on port 5858
debug> connecting to localhost:5858 ... ok
debug> break in timers.js:57
 55 };
 56 
>57 function listOnTimeout() {
 58   var msecs = this.msecs;
 59   var list = this;
debug> c
There was an internal error in Node's debugger. Please report this bug.
read EIO

Error: read EIO
    at exports._errnoException (util.js:856:11)
    at TTY.onread (net.js:545:26)
debug> debug> Segmentation fault (core dumped)
```

I dont have any logging to offer - pardon me if the above is off topic for this issue.

protractor.conf.js looks as follow:

```
exports.config = {
    seleniumAddress: 'http://localhost:4444/wd/hub',
    specs: ['e2e/**/*.js'],
    framework: 'jasmine',
    capabilities: {
        browserName: 'chrome'
    }
};
```
