### ISSUE TITLE
os.cpus() undefined on 2nd call in QEMU on OpenBSD 5.5, node v0.10.24

### ISSUE THREAD

**Issue by systmkor** [nodejs/node-v0.x-archive#8177]
# Source Code

_The example code that produces the error is below._

$ cat cpus.js

``` javascript
var os = require('os');
console.log(os.cpus());
console.log(os.cpus().length);
```
# Log

_Here is the stdout and stderr I receive from running cpus.js._

$ cat cpus.log

```
[ { model: 'QEMU Virtual CPU version 2.1.0',
    speed: 2394,
    times: { user: 956580, nice: 0, sys: 504100, idle: 36342670, irq: 53830 } } ]

/home/systmkor/cpus.js:3
console.log(os.cpus().length);
                     ^
TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (/home/systmkor/cpus.js:3:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by jasnell** [comment]
@systmkor ... I know it's been a while but is this still an issue for you?
