### ISSUE TITLE
UDP datagram sockets don't seem to close properly when on a cluster.Worker

### ISSUE THREAD

**Issue by jcmoore** [nodejs/node-v0.x-archive#8195]
Tested Mac OSX Mavericks in node.js 0.11.12 and 0.11.13 (hope that's recent enough).

Assertion will be thrown when doing the following:

https://gist.github.com/jcmoore/0ee16fe8fcfbe1a19f4c

My logs are as follows:

```
cluster internalMessage: online
sockets 0
sockets 1
cluster internalMessage: queryServer
cluster.queryServer: worker[86366, 1] (0.0.0.0:0:udp4:-1)
cluster internalMessage: undefined
sockets 2
cluster internalMessage: queryServer
cluster.queryServer: worker[86366, 1] (0.0.0.0:0:udp4:-1)
cluster.queryServer: CONFLICT! worker[86366, 1] (0.0.0.0:0:udp4:-1)

assert.js:98
  throw new assert.AssertionError({
        ^
AssertionError: false == true
    at SharedHandle.add (cluster.js:77:3)
    at queryServer (cluster.js:402:12)
    at Worker.onmessage (cluster.js:360:7)
    at ChildProcess.<anonymous> (cluster.js:611:8)
    at ChildProcess.<anonymous> (/Users/jmoore/Sites/toast/toast/sandbox/test.js:109:23)
    at ChildProcess.EventEmitter.emit (events.js:129:20)
    at handleMessage (child_process.js:323:10)
    at Pipe.channel.onread (child_process.js:351:11)
```

**Comment by tjmehta** [comment]
+1

**Comment by anandkumarpatel** [comment]
+1

**Comment by tjmehta** [comment]
This problem seems to be occurring in with Node v0.12.2 on OSX Mavericks (and ubuntu 14.04)
