### ISSUE TITLE
Error: stream.push() after EOF

### ISSUE THREAD

**Issue by maserg** [nodejs/node-v0.x-archive#8216]
hello.

I found that type of error (node v0.10.31, Ubuntu 12.04.5)

```
Error: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:146:15)
    at IncomingMessage.Readable.push (_stream_readable.js:127:10)
    at HTTPParser.parserOnBody [as onBody] (http.js:142:22)
    at CleartextStream.socketOnData [as ondata] (http.js:1583:20)
    at CleartextStream.read [as _read] (tls.js:513:12)
    at CleartextStream.Readable.read (_stream_readable.js:340:10)
    at Object.CleartextStream._handle.readStart (tls.js:744:12)
    at readStart (http.js:42:18)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:177:3)
    at CleartextStream.socketErrorListener (http.js:1554:12)
    at CleartextStream.emit (events.js:117:20)
    at Socket.onerror (tls.js:1442:17)
    at Socket.emit (events.js:117:20)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
```

**Comment by brendanashworth** [comment]
We really need a reproduceable test case in order to help you out. If you can manage to get one going, please open a new issue @ https://github.com/nodejs/node with all the information and link back to this issue. Thanks!

Closing as it is an old issue and not reproduceable as-is.
