### ISSUE TITLE
/test-timers-ordering.js - a test failing since v10.31

### ISSUE THREAD

**Issue by vsacheti** [nodejs/node-v0.x-archive#8330]
AssertionError: current ts 1408497686840 < prev ts 1408497686840 + 1
    at f (....../test/simple/test-timers-ordering.js:41:5)
    at timer._onTimeout (timers.js:219:16)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

**Comment by brendanashworth** [comment]
I'm going to go ahead and close this for inactivity, as it has been a year. This hasn't failed in the node CI anytime lately, afaik, so this is most probably due to weird circumstantial issues.
