### ISSUE TITLE
Unexpected error with getPeerCertificate()

### ISSUE THREAD

**Issue by mscdex** [nodejs/node-v0.x-archive#8381]
Executing this (at least on v0.10.30, v0.11.13+ seems to be fine):

```javascript
https.get('https://google.com', function(res) {
  console.dir(res.socket.getPeerCertificate());
});
```

results in:

```
{ subject:
   { C: 'US',
     ST: 'California',
     L: 'Mountain View',
     O: 'Google Inc',
     CN: '*.google.com' },
  issuer: { C: 'US', O: 'Google Inc', CN: 'Google Internet Authority G2' },
  subjectaltname: 'DNS:*.google.com, DNS:*.android.com, DNS:*.appengine.google.com, DNS:*.cloud.google.com, DNS:*.google-analytics.com, DNS:*.google.ca, DNS:*.google.cl, DNS:*.google.co.in, DNS:*.google.co.jp, DNS:*.google.co.uk, DNS:*.google.com.ar, DNS:*.google.com.au, DNS:*.google.com.br, DNS:*.google.com.co, DNS:*.google.com.mx, DNS:*.google.com.tr, DNS:*.google.com.vn, DNS:*.google.de, DNS:*.google.es, DNS:*.google.fr, DNS:*.google.hu, DNS:*.google.it, DNS:*.google.nl, DNS:*.google.pl, DNS:*.google.pt, DNS:*.googleadapis.com, DNS:*.googleapis.cn, DNS:*.googlecommerce.com, DNS:*.googlevideo.com, DNS:*.gstatic.cn, DNS:*.gstatic.com, DNS:*.gvt1.com, DNS:*.urchin.com, DNS:*.url.google.com, DNS:*.youtube-nocookie.com, DNS:*.youtube.com, DNS:*.youtubeeducation.com, DNS:*.ytimg.com, DNS:android.com, DNS:g.co, DNS:goo.gl, DNS:google-analytics.com, DNS:google.com, DNS:googlecommerce.com, DNS:urchin.com, DNS:youtu.be, DNS:youtube.com, DNS:youtubeeducation.com',
  valid_from: 'Aug 27 11:47:20 2014 GMT',
  valid_to: 'Nov 25 00:00:00 2014 GMT',
  fingerprint: 'DC:C8:C5:F7:4F:2A:9E:3C:02:CF:EC:C6:87:59:CC:5A:30:03:DB:F8',
  ext_key_usage: [ '1.3.6.1.5.5.7.3.1', '1.3.6.1.5.5.7.3.2' ] }

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: 4516:error:0607907F:digital envelope routines:EVP_PKEY_get1_RSA:expecting an rsa key:openssl\crypto\evp\p_lib.c:288:

    at SlabBuffer.use (tls.js:234:18)
    at CleartextStream.read [as _read] (tls.js:454:29)
    at CleartextStream.Readable.read (_stream_readable.js:340:10)
    at CleartextStream.read [as _read] (tls.js:519:12)
    at CleartextStream.Readable.read (_stream_readable.js:340:10)
    at EncryptedStream.write [as _write] (tls.js:368:25)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at EncryptedStream.Writable.write (_stream_writable.js:182:11)
    at write (_stream_readable.js:601:24)
```

**Comment by brendanashworth** [comment]
I guess I'll close this in favor of discussion @ https://github.com/nodejs/node/issues/5035.
