### ISSUE TITLE
0.10.32 error when calling end() on a TLS connection opened with an expired or bad certificate

### ISSUE THREAD

**Issue by tanis2000** [nodejs/node-v0.x-archive#8623]
I'm experiencing the following error when trying to open a new TLS connection with an expired certificate:

```
4116:error:14094415:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate expired:openssl\ssl\s3_pkt.c:1275:SSL alert number 45

2014-10-27T11:28:14.226Z - error: uncaughtException: Cannot read property 'error' of null
TypeError: Cannot read property 'error' of null,
     at SecurePair.error (tls.js:1004:21),
     at EncryptedStream.CryptoStream._done (tls.js:702:22),
     at CleartextStream.onCryptoStreamFinish (tls.js:309:54),
     at CleartextStream.g (events.js:180:16),
     at CleartextStream.emit (events.js:92:17),
     at finishMaybe (_stream_writable.js:359:12),
     at endWritable (_stream_writable.js:366:3),
     at CleartextStream.Writable.end (_stream_writable.js:344:5),
     at CleartextStream.CryptoStream.end (tls.js:640:31),
     at Connection.<anonymous> (c:\lavori\itablo-web\NodePushService\node_modules\apn\lib\connection.js:194:17)]
```

Line 194 of connection.js is the following: https://github.com/argon/node-apn/blob/master/lib/connection.js#L194

Is there anything I can do to help debug this? It's kind of a real problem unless there is a way to check an SSL certificate to see if it's either bad or expired.

Thanks!

**Comment by lalop** [comment]
Hy,
there is  any news on that ?

**Comment by indutny** [comment]
Oh gosh, it got lost in my backlog.
