### ISSUE TITLE
Cannot call method 'loadSession' of null

### ISSUE THREAD

**Issue by Rush** [nodejs/node-v0.x-archive#8710]
Got at node 0.10.33, happened couple of times recently. Could this be a node problem? @indutny 
Looks kinda weird that `this` is null in the node code of `onclienthello`.

```
TypeError: Cannot call method 'loadSession' of null
    at callback (tls.js:836:14)
    at process.<anonymous> (/usr/lib/node_modules/http-master/worker.js:48:9)
    at process.g (events.js:180:16)
    at process.emit (events.js:95:17)
    at process.on.config (/usr/lib/node_modules/http-master/worker.js:77:11)
    at process.emit (events.js:117:20)
    at handleMessage (child_process.js:322:10)
    at Pipe.channel.onread (child_process.js:349:11)
```

This is the tls code in node:

``` js
function onclienthello(hello) {
  var self = this,
      once = false;

  this._resumingSession = true;
  function callback(err, session) {
    if (once) return;
    once = true;

    if (err) return self.socket.destroy(err);

    self.ssl.loadSession(session); // <--- this is the tls.js line from stacktrace
```

Secure context is created with:

``` js
    crypto.createCredentials(stuff).context;
```

**Comment by jasnell** [comment]
@indutny .... ;-) much longer than 28 days now. Any updates?
