### ISSUE TITLE
A number of crypto ciphers are not working properly

### ISSUE THREAD

**Issue by CGavrila** [nodejs/node-v0.x-archive#8783]
I ran the following code on v0.10.33 and v0.11.14, both have the same issue.

The script simply goes through all the available ciphers, encrypts a string, decrypts it and then checks if the original one is the same as the decrypted one.

```
var crypto = require('crypto');
var assert = require('assert');

var key = 'some_salt_right_here'
  , plaintext = 'password';

var CIPHERS = crypto.getCiphers();

/*
 *  Uncomment this in order to run only with the "good" ciphers.
 *
var bad_ciphers = [ 'aes-128-cbc-hmac-sha1',
                    'aes-128-gcm',
                    'aes-128-xts',
                    'aes-192-gcm',
                    'aes-256-cbc-hmac-sha1',
                    'aes-256-gcm',
                    'aes-256-xts',
                    'id-aes128-GCM',
                    'id-aes192-GCM',
                    'id-aes256-GCM'];

for (var i=0; i < bad_ciphers.length; i++) {
    var index = CIPHERS.indexOf(bad_ciphers[i]);
    CIPHERS.splice(index, 1);
}
*/

for (var i=0; i<CIPHERS.length; i++) {
        console.log('Using cipher: ' + CIPHERS[i]);
        var cipher = crypto.createCipher(CIPHERS[i], plaintext)
          , decipher = crypto.createDecipher(CIPHERS[i], plaintext);

        var cipher1 = cipher.update(plaintext, 'utf8', 'hex');
        cipher1 += cipher.final('hex')

        var decipher1 = decipher.update(cipher1, 'hex', 'utf8');
        decipher1 += decipher.final('utf8');

        console.log(cipher1);
        console.log(decipher1);

        assert.notEqual(plaintext, cipher1);
        assert.equal(plaintext, decipher1);
}
```

However, this fails for a number of ciphers: `aes-128-gcm, aes-128-xts, aes-192-gcm, aes-256-cbc-hmac-sha1, aes-256-gcm, aes-256-xts, des-ede3-cfb1, id-aes128-GCM, id-aes192-GCM, id-aes256-GCM` with the following error:

```
crypto.js:201
  var ret = this._handle.final();
                         ^
Error: Unsupported state or unable to authenticate data
    at Error (native)
    at Decipher.Cipher.final (crypto.js:201:26)
    at Object.<anonymous> (/home/cristian/work/performance/gbench/tests/crypto/cipher-test/cipher-test.js:34:31)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:124:16)
    at node.js:842:3
```

A couple of them have some explanation:
1. `aes-128-xts, aes-256-xts` - need to have an input of `>=16 bytes`  - #6477
2. `aes-256-cbc-hmac-sha1` - mentioned in issues #7583 and #7583, but no example of how this might work

The `des-ede3-cfb1` cipher is a special case since the decrypted string does not match the one it encrypted:

```
************************************** node v0.10.33 **************************************
assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: "password" == "p\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
    at Object.<anonymous> (/home/cristian/work/performance/gbench/tests/crypto/cipher-test/cipher-test.js:40:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

Using cipher: des-ede3-cfb1
Original password: password
Encrypted password: 8700000000000000
Decrypted password: p

************************************** node v0.11.14 **************************************
assert.js:98
  throw new assert.AssertionError({
        ^
AssertionError: "password" == "p��\u0011\u0000\u0000\u0000"
    at Object.<anonymous> (/home/cristian/work/performance/gbench/tests/crypto/cipher-test/cipher-test.js:40:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:124:16)
    at node.js:842:3

Using cipher: des-ede3-cfb1
Original password: password
Encrypted password: 87878711007f0000
Decrypted password: p��
```

For all the other ciphers which are not working, I didn't find any references online.

Should this at least be documented somehow?

**Comment by timmclean** [comment]
You need to use [setAuthTag](https://nodejs.org/api/crypto.html#crypto_decipher_setauthtag_buffer) when using authenticated encryption modes
