### ISSUE TITLE
repl parsing error.

### ISSUE THREAD

**Issue by llafuente** [nodejs/node-v0.x-archive#8891]
Hi,

`var -name` (enter) should give an error... as Node does.

```bash
luis@luis-dev:~/node -v
v0.10.26

luis@luis-dev:~/noboxout/language$ node
> var -name;
... 
> 
(^C again to quit)
> 
luis@luis-dev:~/noboxout/language$ node -e "var -name"

[eval]:1
var -name
    ^
SyntaxError: Unexpected token -
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:532:25)
    at startup (node.js:80:7)
    at node.js:902:3
```

**Comment by llafuente** [comment]
This is still a bug, maybe can be closed as wontfix...

``` sh
[luis@ ~]node -v
v4.4.0
[luis@ ~]node
> var -name;
... 
... 
> 
(To exit, press ^C again or type .exit)
> 
```

**Comment by bnoordhuis** [comment]
I can confirm master is still affected, but given how the REPL works, I'm not sure if it's something that can be properly fixed.

I'll close the issue.  If you still wish to pursue it, please file a new one here: https://github.com/nodejs/node/issues
