### ISSUE TITLE
Unexpected Null In Loop Of Read Stream

### ISSUE THREAD

**Issue by blyork** [nodejs/node-v0.x-archive#9228]
Description:
I ran into the below error when using streams. According to my debugger, state.pipesCount is 0 and state.pipes is null when reaching the forEach.

System Info:

```
OS: Ubuntu 14.04 LTS
Architecture: x86_64
Node Version: v0.10.36
```

Stack Trace:

```
_stream_readable.js:613
      state.pipes.forEach(write);
                  ^
TypeError: Cannot call method 'forEach' of null
    at flow (_stream_readable.js:613:19)
    at WriteStream.<anonymous> (_stream_readable.js:592:7)
    at WriteStream.emit (events.js:92:17)
    at onwriteDrain (_stream_writable.js:289:12)
    at afterWrite (_stream_writable.js:277:5)
    at onwrite (_stream_writable.js:270:7)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at fs.js:1695:5
    at Object.wrapper [as oncomplete] (fs.js:522:5)
```

Containing Function In _stream_readable.js:

``` javascript
function flow(src) {
  var state = src._readableState;
  var chunk;
  state.awaitDrain = 0;

  function write(dest, i, list) {
    var written = dest.write(chunk);
    if (false === written) {
      state.awaitDrain++;
    }
  }

  while (state.pipesCount && null !== (chunk = src.read())) {

    if (state.pipesCount === 1)
      write(state.pipes, 0, null);
    else
      state.pipes.forEach(write);

    src.emit('data', chunk);

    // if anyone needs a drain, then we have to wait for that.
    if (state.awaitDrain > 0)
      return;
  }

  // if every destination was unpiped, either before entering this
  // function, or in the while loop, then stop flowing.
  //
  // NB: This is a pretty rare edge case.
  if (state.pipesCount === 0) {
    state.flowing = false;

    // if there were data event listeners added, then switch to old mode.
    if (EE.listenerCount(src, 'data') > 0)
      emitDataEvents(src);
    return;
  }

  // at this point, no one needed a drain, so we just ran out of data
  // on the next readable event, start it over again.
  state.ranOut = true;
}
```

**Comment by CGavrila** [comment]
Do you happen to have a simple test case for this?
